// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlnAl-7qzJACxBR-dYO5YT8Dm_Qh7Ss3M',
    appId: '1:820215146068:web:147531416061d098a76fc1',
    messagingSenderId: '820215146068',
    projectId: 'coreh-400d0',
    authDomain: 'coreh-400d0.firebaseapp.com',
    storageBucket: 'coreh-400d0.firebasestorage.app',
    measurementId: 'G-YT7HTRL4PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0WbWHKI-906ZtPvFiJy0hMPihGyxe8ZI',
    appId: '1:820215146068:android:1836544b1e365a9fa76fc1',
    messagingSenderId: '820215146068',
    projectId: 'coreh-400d0',
    storageBucket: 'coreh-400d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyZdpfnlgtp1zTPrzCVCpkKOXiIQ-Kgow',
    appId: '1:820215146068:ios:080eddd97846c1a3a76fc1',
    messagingSenderId: '820215146068',
    projectId: 'coreh-400d0',
    storageBucket: 'coreh-400d0.firebasestorage.app',
    iosBundleId: 'com.example.coreh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyZdpfnlgtp1zTPrzCVCpkKOXiIQ-Kgow',
    appId: '1:820215146068:ios:080eddd97846c1a3a76fc1',
    messagingSenderId: '820215146068',
    projectId: 'coreh-400d0',
    storageBucket: 'coreh-400d0.firebasestorage.app',
    iosBundleId: 'com.example.coreh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlnAl-7qzJACxBR-dYO5YT8Dm_Qh7Ss3M',
    appId: '1:820215146068:web:55faa896fd6ea6eda76fc1',
    messagingSenderId: '820215146068',
    projectId: 'coreh-400d0',
    authDomain: 'coreh-400d0.firebaseapp.com',
    storageBucket: 'coreh-400d0.firebasestorage.app',
    measurementId: 'G-M3VWD395G4',
  );
}
